import Link from "../components/static-link";

export default function ResearchPage() {
  return <main className="container research-page"><div className="breadcrumbs"><Link href="/">Início</Link> / Como escolhemos</div><span className="eyebrow">CURADORIA NORDLY</span><h1>Menos opções. Mais clareza para escolher.</h1><p className="product-lead">Cada item publicado precisa ter modelo identificável, ficha técnica consistente, imagem rastreável e um benefício real para o comprador.</p>
    <section className="research-summary"><div><strong>100%</strong><span>dos itens com modelo</span></div><div><strong>0</strong><span>produtos genéricos Nordly</span></div><div><strong>0</strong><span>wireless sem ANATEL</span></div><div><strong>1 fonte</strong><span>de dados para loja e operação</span></div></section>
    <section className="method-public-grid"><article><span>01</span><h2>Identidade verificável</h2><p>Marca, modelo, variação e características precisam apontar para um produto real. Nada de nome genérico criado para preencher prateleira.</p></article><article><span>02</span><h2>Compatibilidade explícita</h2><p>Plataforma, conexão, tamanho e limitações aparecem na página antes de você adicionar ao carrinho.</p></article><article><span>03</span><h2>Imagem com origem</h2><p>A foto principal é armazenada localmente para estabilidade e registra a página oficial usada como referência.</p></article><article><span>04</span><h2>Preço que faz sentido</h2><p>A vitrine mostra preço, condição no Pix e parcelamento. Custos internos e decisões de operação ficam restritos ao painel administrativo.</p></article></section>
    <section className="research-section"><h2>O que fica fora</h2><div className="discards"><div className="discard"><strong>Produto sem modelo</strong><span>Não entra até identificação e ficha técnica confiáveis.</span></div><div className="discard"><strong>Wireless sem homologação</strong><span>Não é ativado sem confirmação aplicável da ANATEL.</span></div><div className="discard"><strong>Promessa sem evidência</strong><span>Benefícios são descritos a partir de especificações verificáveis.</span></div></div></section>
    <Link className="button button-dark" href="/catalogo">Explorar catálogo →</Link>
  </main>;
}
