import Link from "next/link";
import { brl, products } from "../lib/products";

const sources=[
  ["Receita Federal — tributação de remessas","https://www.gov.br/receitafederal/pt-br/assuntos/aduana-e-comercio-exterior/manuais/remessas-postal-e-expressa/preciso-pagar-impostos-nas-compras-internacionais/quais-sao-os-impostos-devidos"],
  ["Anatel — certificação de produtos","https://www.gov.br/anatel/pt-br/regulado/certificacao-de-produtos"],
  ["Anatel — dúvidas sobre Wi‑Fi e Bluetooth","https://www.gov.br/anatel/pt-br/regulado/certificacao-de-produtos/duvidas-frequentes"],
  ["Mercado Pago — Webhooks","https://www.mercadopago.com.br/developers/pt/docs/your-integrations/notifications/webhooks"],
  ["CJ Dropshipping — API v2","https://developers.cjdropshipping.com/en/api/api2/"],
  ["CJ Dropshipping — Sandbox","https://developers.cjdropshipping.com/en/api/start/sandbox.html"],
  ["AutoDS — API e automação","https://help.autods.com/en/articles/12699964-autods-api-feature-automate-product-imports-orders-and-sourcing"],
  ["ANPD — segurança para pequenos agentes","https://www.gov.br/anpd/pt-br/assuntos/noticias/anpd-publica-guia-de-seguranca-para-agentes-de-tratamento-de-pequeno-porte"],
  ["KaBuM — homepage e ofertas","https://www.kabum.com.br/"],
  ["Pichau — hardware","https://www.pichau.com.br/hardware"],
  ["TerabyteShop — ofertas","https://www.terabyteshop.com.br/ofertas"],
  ["Mercado Livre — GameSir G7 SE","https://www.mercadolivre.com.br/loja/gamesir-406306"],
  ["Mercado Livre — FIFINE AM8","https://lista.mercadolivre.com.br/fifine-am8"],
];

export default function ResearchPage(){return <main><section className="page-hero"><div className="container"><div className="breadcrumbs"><Link href="/">Início</Link> / Pesquisa</div><span className="eyebrow">RELATÓRIO DE DECISÃO · 30/08/2026</span><h1>O que entra, o que sai<br/>e por quê.</h1><p>Pesquisa enxuta que sustenta a primeira versão. Dado observado, estimativa e mock aparecem separados; estoque e vendas nunca são inventados.</p></div></section><div className="container research-page"><div className="research-summary"><div><strong>15</strong><span>SKUs APROVADOS PARA VALIDAÇÃO</span></div><div><strong>5</strong><span>HERO PRODUCTS</span></div><div><strong>41,6%</strong><span>MARGEM PRÉ-CAC MÉDIA EST.</span></div><div><strong>7</strong><span>GRUPOS CONCORRENTES</span></div></div>
  <section className="research-section"><span className="eyebrow">01 · MERCADO E CONCORRÊNCIA</span><h2>Padrões que convertem — sem copiar ninguém</h2><p>KaBuM, Pichau e Terabyte reforçam busca forte, categorias, preço à vista/Pix e parcelamento. Marketplaces elevam a expectativa por comparação, frete calculado e avaliações. A síntese Nordly usa esses padrões, mas troca urgência artificial por transparência de origem, margem e critério de curadoria.</p><ul><li><b>Header:</b> busca central dominante, categorias escaneáveis, conta, favoritos e carrinho.</li><li><b>Card:</b> Pix primeiro, preço parcelado logo abaixo, benefício e CTA claro.</li><li><b>Confiança:</b> prazo por origem, tracking, política de troca e avaliações somente verificadas.</li><li><b>Diferenciação:</b> score, margem pré-CAC e motivo de aprovação publicados no produto.</li></ul></section>
  <section className="research-section"><span className="eyebrow">02 · CATÁLOGO E UNIT ECONOMICS</span><h2>15 SKUs, não 150 apostas</h2><p>Custos e margens abaixo são <b>ESTIMATIVAS</b> para decisão inicial; exigem cotação final, câmbio e frete por CEP antes de ativar venda. A fórmula considera produto, frete, tributos, gateway/parcelamento, operação e reservas.</p><div className="risk-table-wrap"><table className="data-table"><thead><tr><th>Produto</th><th>Papel</th><th>Fornecedor</th><th>Backup</th><th>Custo op.</th><th>Mercado</th><th>Pix</th><th>Margem</th><th>CAC máx.</th><th>Score</th><th>SLA</th><th>Risco</th></tr></thead><tbody>{products.map(product=><tr key={product.id}><td><b>{product.shortName}</b></td><td>{product.role}</td><td>{product.supplier.split(" (")[0]}</td><td>{product.backup.split(" (")[0]}</td><td>{brl(product.operatingCost)}</td><td>{product.marketRange}</td><td>{brl(product.pixPrice)}</td><td>{product.margin.toFixed(1)}%</td><td>{brl(product.preCac)}</td><td>{product.score.toFixed(1)}</td><td>{product.sla}</td><td>{product.risk}</td></tr>)}</tbody></table></div><p><small><b>Sem dados públicos confiáveis de vendas mensais:</b> GMV não foi calculado. Campo permanece “não disponível” em vez de receber um número inventado. Supplier score é avaliação preliminar de marca/canal, não auditoria contratual.</small></p></section>
  <section className="research-section"><span className="eyebrow">03 · COMPLIANCE</span><h2>O corte mais importante foi regulatório</h2><p>A Anatel informa que a homologação é pré-requisito para comercialização de produtos de telecomunicações e cita dispositivos Wi‑Fi/Bluetooth como sujeitos à regra. Por isso, a primeira seleção privilegia produtos com fio ou passivos. Mouse, teclado, headset e TWS sem fio só voltam ao funil com certificado do modelo e cadeia de comercialização validada.</p><p>Na tributação, a Receita informa as regras do RTS/Remessa Conforme vigentes na data da pesquisa, com tratamento diferente por faixa de valor e por participante certificado. A planilha operacional deve recalcular II e ICMS por operação; a modelagem desta versão não é parecer fiscal.</p></section>
  <section className="research-section"><span className="eyebrow">04 · DESCARTADOS</span><h2>Vender muito não é passar no filtro</h2><div className="discards"><div className="discard"><strong>Attack Shark X3 / VXE R1</strong><span>ALTO RISCO · Sem comprovação de homologação do modelo e cadeia de venda no momento da pesquisa.</span></div><div className="discard"><strong>AULA F75 / Ajazz AK820 Pro</strong><span>ATENÇÃO · Versões trimode misturam variantes e compliance; risco de variante errada e pós-venda.</span></div><div className="discard"><strong>Fones TWS genéricos</strong><span>DESCARTADO · Saturação, devolução, bateria, qualidade variável e exigência Anatel.</span></div><div className="discard"><strong>SSD/RAM sem distribuidor</strong><span>DESCARTADO · Risco de falsificação, garantia, variação cambial e margem comprimida.</span></div><div className="discard"><strong>Carregadores sem certificação</strong><span>DESCARTADO · Segurança elétrica e responsabilidade de pós-venda acima do aceitável.</span></div><div className="discard"><strong>Webcam sem marca</strong><span>DESCARTADO · Qualidade imprevisível e baixa diferenciação frente ao mercado nacional.</span></div></div></section>
  <section className="research-section"><span className="eyebrow">05 · FORNECEDORES E AUTOMAÇÃO</span><h2>API antes de clique; sandbox antes de dinheiro</h2><p>CJ documenta produtos, estoque, frete, criação de pedido, tracking, webhooks e sandbox. AutoDS documenta API e automação sujeitas a aprovação e configuração. A arquitetura usa uma camada de adaptadores e mantém compra real bloqueada até credenciais, contrato, validação de margem e testes de idempotência.</p><div className="flow-row"><span>Pagamento aprovado</span><i>→</i><span>Antifraude</span><i>→</i><span>Endereço</span><i>→</i><span>Estoque + preço</span><i>→</i><span>Margem + SLA</span><i>→</i><span>Compliance</span><i>→</i><span>Autorizar / manual_review</span><i>→</i><span>Fornecedor</span><i>→</i><span>Tracking</span></div></section>
  <section className="research-section"><span className="eyebrow">06 · FONTES</span><h2>Links e tipo do dado</h2><p>Todas consultadas em 30/08/2026. Fontes oficiais sustentam regra, especificação e integração; marketplaces funcionam como proxy de preço e demanda, nunca como prova de lucro.</p><ul>{sources.map(([label,url])=><li key={url}><a href={url} target="_blank" rel="noreferrer">{label}</a> — {label.includes("Receita")||label.includes("Anatel")||label.includes("ANPD")||label.includes("Mercado Pago")||label.includes("CJ")||label.includes("AutoDS")?"DADO REAL / fonte oficial":"PROXY de mercado"}</li>)}</ul></section>
</div></main>}

