import { products, brl } from "../lib/products";

const alerts=[{level:"high",title:"3 SKUs sem fornecedor contratado",detail:"Bloqueados para venda real"},{level:"",title:"Câmbio com atualização pendente",detail:"Buffer de 6% aplicado"},{level:"",title:"CJ Adapter em sandbox",detail:"Nenhuma compra real autorizada"},{level:"high",title:"Produtos wireless descartados",detail:"Homologação Anatel não comprovada"}];

export default function AdminPage(){
  const avgMargin=products.reduce((sum,p)=>sum+p.margin,0)/products.length;
  return <main className="admin-page"><div className="container"><header className="admin-head"><div><span className="eyebrow">CENTRO OPERACIONAL</span><h1>Visão geral</h1></div><span className="mock-pill">● SANDBOX / DADOS SIMULADOS</span></header><section className="metric-grid"><div className="metric"><span>GMV</span><strong>R$ 0</strong><small>Sem vendas reais</small></div><div className="metric"><span>PEDIDOS</span><strong>0</strong><small>Produção desativada</small></div><div className="metric"><span>MARGEM PRÉ-CAC</span><strong>{avgMargin.toFixed(1)}%</strong><small>Catálogo estimado</small></div><div className="metric"><span>SKUS ATIVOS</span><strong>{products.length}</strong><small>Em validação</small></div><div className="metric"><span>REVISÃO MANUAL</span><strong>3</strong><small>Mock operacional</small></div></section><div className="admin-grid"><section className="admin-card"><h2>Catálogo e proteção de margem</h2><div style={{overflowX:"auto"}}><table className="data-table"><thead><tr><th>SKU</th><th>Papel</th><th>Preço Pix</th><th>Custo</th><th>Margem</th><th>Supplier</th><th>Status</th></tr></thead><tbody>{products.slice(0,8).map(product=><tr key={product.id}><td><b>{product.shortName}</b></td><td>{product.role}</td><td>{brl(product.pixPrice)}</td><td>{brl(product.operatingCost)}</td><td>{product.margin.toFixed(1)}%</td><td>{product.supplierScore.toFixed(1)}</td><td><span className="status-pill review">Qualificação</span></td></tr>)}</tbody></table></div></section><section className="admin-card"><h2>Alertas prioritários</h2><div className="alert-list">{alerts.map(alert=><div className={`alert ${alert.level}`} key={alert.title}><i/><b>{alert.title}</b><small>{alert.detail}</small></div>)}</div></section><section className="admin-card"><h2>Pipeline de pedido</h2><div className="flow-row"><span>paid</span><i>→</i><span>fraud_review</span><i>→</i><span>supplier_check</span><i>→</i><span>manual_review</span><i>→</i><span>supplier_ordered</span><i>→</i><span>shipped</span></div><p className="summary-note">Fallback padrão: qualquer falha de API, estoque, preço, SLA, tracking, endereço ou compliance move o pedido para <b>manual_review</b>. Reprocessamento exige a mesma chave de idempotência.</p></section><section className="admin-card"><h2>Integrações</h2><table className="data-table"><tbody><tr><td>Mercado Pago</td><td>Não conectado</td><td><span className="status-pill review">Sandbox planejado</span></td></tr><tr><td>CJ Dropshipping</td><td>Adapter preparado</td><td><span className="status-pill review">Mock</span></td></tr><tr><td>AutoDS</td><td>Em avaliação</td><td><span className="status-pill review">Não conectado</span></td></tr><tr><td>Analytics</td><td>Eventos mapeados</td><td><span className="status-pill">Pronto p/ configuração</span></td></tr></tbody></table></section></div></div></main>
}

