import { brl, products } from "../lib/products";

export default function AdminPage() {
  const margins = products.map((product) => product.operations.margin).filter((value): value is number => value !== null);
  const avgMargin = margins.reduce((sum, value) => sum + value, 0) / margins.length;
  const pending = products.filter((product) => product.operations.status === "pending");
  const missingMedia = products.filter((product) => !product.media.length);
  const requiredGroups = ["category", "type", "price", "use"] as const;
  const insufficientTags = products.filter((product) => product.tags.length < 6 || requiredGroups.some((group) => !product.tags.some((tag) => {
    if (group === "category") return tag === product.categorySlug || tag === "acessorios";
    if (group === "type") return ["controle", "microfone", "mixer", "headset", "mouse", "teclado", "memoria-ram", "hub-usb-c", "case-nvme", "suporte-notebook", "luminaria", "cabo-usb-c"].includes(tag);
    if (group === "price") return ["ate-100", "100-200", "200-300", "300-500", "acima-500"].includes(tag);
    return ["gaming", "streaming", "home-office", "upgrade", "mobilidade", "produtividade", "criacao-conteudo", "podcast", "upgrade-pc"].includes(tag);
  })));
  return <main className="admin-page"><div className="container">
    <header className="admin-head"><div><span className="eyebrow">CENTRO OPERACIONAL · ACESSO INTERNO</span><h1>Catálogo e operação</h1></div><span className="mock-pill">● DADOS OPERACIONAIS</span></header>
    <section className="metric-grid"><div className="metric"><span>SKUS ATIVOS</span><strong>{products.length}</strong><small>Fonte compartilhada</small></div><div className="metric"><span>MÍDIA COMPLETA</span><strong>{products.length - missingMedia.length}/{products.length}</strong><small>Imagem e origem</small></div><div className="metric"><span>MARGEM MÉDIA</span><strong>{avgMargin.toFixed(1)}%</strong><small>Somente itens cotados</small></div><div className="metric"><span>QUALIFICAÇÃO</span><strong>{pending.length}</strong><small>Fornecedor/custo pendente</small></div><div className="metric"><span>WIRELESS ATIVO</span><strong>0</strong><small>Sem ANATEL confirmado</small></div></section>
    <div className="admin-grid"><section className="admin-card admin-wide"><h2>Fonte única do catálogo</h2><div className="table-scroll"><table className="data-table"><thead><tr><th>SKU / modelo</th><th>Papel</th><th>Preço Pix</th><th>Custo op.</th><th>Margem</th><th>Supplier score</th><th>Fornecedor</th><th>Mídia</th><th>Status</th></tr></thead><tbody>{products.map((product) => <tr key={product.id}><td><b>{product.shortName}</b><small>{product.model}</small></td><td>{product.operations.role}</td><td>{brl(product.pixPrice)}</td><td>{product.operations.operatingCost === null ? "Pendente" : brl(product.operations.operatingCost)}</td><td>{product.operations.margin === null ? "Pendente" : `${product.operations.margin.toFixed(1)}%`}</td><td>{product.operations.supplierScore?.toFixed(1) ?? "Pendente"}</td><td>{product.operations.supplier}</td><td>{product.media.length} · {product.tags.length} tags</td><td><span className={`status-pill ${product.operations.status === "pending" ? "review" : ""}`}>{product.operations.status === "qualified" ? "Qualificado" : "Revisão"}</span></td></tr>)}</tbody></table></div></section>
      <section className="admin-card"><h2>Alertas prioritários</h2><div className="alert-list"><div className="alert high"><i/><b>{pending.length} SKUs sem custo validado</b><small>Não autorizar pedido automático</small></div><div className="alert"><i/><b>{missingMedia.length} imagens principais ausentes</b><small>Fontes e datas verificadas por produto</small></div><div className={`alert ${insufficientTags.length ? "high" : ""}`}><i/><b>{insufficientTags.length ? `${insufficientTags.length} produtos sem tags suficientes` : "Todos os produtos com tags suficientes"}</b><small>Categoria, tipo, preço e uso obrigatórios</small></div><div className="alert"><i/><b>Produtos wireless bloqueados</b><small>Aguardar homologação ANATEL</small></div><div className="alert high"><i/><b>Pagamento não conectado</b><small>Dependência externa</small></div></div></section>
      <section className="admin-card"><h2>Pipeline protegido</h2><div className="flow-row"><span>paid</span><i>→</i><span>fraud_review</span><i>→</i><span>supplier_check</span><i>→</i><span>manual_review</span><i>→</i><span>supplier_ordered</span><i>→</i><span>shipped</span></div><p className="summary-note">Custo, estoque, endereço, compliance e preço precisam estar confirmados antes da compra no fornecedor. Qualquer divergência segue para revisão manual.</p></section>
    </div>
  </div></main>;
}
