import { index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

const timestamps = { createdAt: text("created_at").notNull(), updatedAt: text("updated_at").notNull() };

export const users = sqliteTable("users", { id: text("id").primaryKey(), email: text("email").notNull(), name: text("name"), ...timestamps }, (table)=>[uniqueIndex("idx_users_email").on(table.email)]);
export const addresses = sqliteTable("addresses", { id:text("id").primaryKey(), userId:text("user_id"), name:text("name").notNull(), line1:text("line1").notNull(), city:text("city").notNull(), state:text("state").notNull(), postalCode:text("postal_code").notNull(), country:text("country").notNull().default("BR"), phone:text("phone"), ...timestamps },(table)=>[index("idx_addresses_user_id").on(table.userId)]);
export const suppliers = sqliteTable("suppliers", { id:text("id").primaryKey(), name:text("name").notNull(), adapter:text("adapter").notNull(), status:text("status").notNull().default("qualification"), score:real("score"), country:text("country"), automationMode:text("automation_mode").notNull().default("mock"), ...timestamps });
export const products = sqliteTable("products", { id:text("id").primaryKey(), slug:text("slug").notNull(), brand:text("brand").notNull(), name:text("name").notNull(), category:text("category").notNull(), role:text("role").notNull(), status:text("status").notNull().default("validation"), complianceStatus:text("compliance_status").notNull(), score:real("score"), ...timestamps },(table)=>[uniqueIndex("idx_products_slug").on(table.slug),index("idx_products_status_category").on(table.status,table.category)]);
export const variants = sqliteTable("variants", { id:text("id").primaryKey(), productId:text("product_id").notNull(), sku:text("sku").notNull(), name:text("name").notNull(), status:text("status").notNull().default("active"), ...timestamps },(table)=>[uniqueIndex("idx_variants_sku").on(table.sku),index("idx_variants_product_id").on(table.productId)]);
export const supplierProducts = sqliteTable("supplier_products", { id:text("id").primaryKey(), supplierId:text("supplier_id").notNull(), variantId:text("variant_id").notNull(), externalId:text("external_id"), currency:text("currency").notNull().default("BRL"), unitCost:real("unit_cost").notNull(), freightCost:real("freight_cost").notNull().default(0), isPrimary:integer("is_primary",{mode:"boolean"}).notNull().default(false), ...timestamps },(table)=>[index("idx_supplier_products_variant").on(table.variantId),index("idx_supplier_products_supplier").on(table.supplierId)]);
export const priceHistory = sqliteTable("price_history", { id:integer("id").primaryKey({autoIncrement:true}), variantId:text("variant_id").notNull(), supplierProductId:text("supplier_product_id"), currency:text("currency").notNull(), supplierCost:real("supplier_cost").notNull(), operatingCost:real("operating_cost").notNull(), salePrice:real("sale_price").notNull(), marginPercent:real("margin_percent").notNull(), capturedAt:text("captured_at").notNull() },(table)=>[index("idx_price_history_variant_date").on(table.variantId,table.capturedAt)]);
export const inventory = sqliteTable("inventory", { id:text("id").primaryKey(), variantId:text("variant_id").notNull(), supplierProductId:text("supplier_product_id").notNull(), available:integer("available",{mode:"boolean"}).notNull(), quantity:integer("quantity"), checkedAt:text("checked_at").notNull(), ...timestamps },(table)=>[index("idx_inventory_variant").on(table.variantId)]);
export const carts = sqliteTable("carts", { id:text("id").primaryKey(), userId:text("user_id"), status:text("status").notNull().default("active"), ...timestamps },(table)=>[index("idx_carts_user_status").on(table.userId,table.status)]);
export const favorites = sqliteTable("favorites", { id:integer("id").primaryKey({autoIncrement:true}), userId:text("user_id").notNull(), productId:text("product_id").notNull(), createdAt:text("created_at").notNull() },(table)=>[uniqueIndex("idx_favorites_user_product").on(table.userId,table.productId)]);
export const orders = sqliteTable("orders", { id:text("id").primaryKey(), idempotencyKey:text("idempotency_key").notNull(), userId:text("user_id"), customerName:text("customer_name").notNull(), customerEmail:text("customer_email").notNull(), postalCode:text("postal_code").notNull(), shippingCity:text("shipping_city").notNull(), shippingState:text("shipping_state").notNull(), paymentMethod:text("payment_method").notNull(), status:text("status").notNull(), mode:text("mode").notNull().default("sandbox"), currency:text("currency").notNull().default("BRL"), total:real("total").notNull(), preCacMargin:real("pre_cac_margin").notNull(), supplierOrderId:text("supplier_order_id"), ...timestamps },(table)=>[uniqueIndex("idx_orders_idempotency").on(table.idempotencyKey),index("idx_orders_status_created").on(table.status,table.createdAt),index("idx_orders_customer_email").on(table.customerEmail)]);
export const orderItems = sqliteTable("order_items", { id:text("id").primaryKey(), orderId:text("order_id").notNull(), productId:text("product_id").notNull(), variantId:text("variant_id"), quantity:integer("quantity").notNull(), unitPrice:real("unit_price").notNull(), unitOperatingCost:real("unit_operating_cost").notNull(), ...timestamps },(table)=>[index("idx_order_items_order").on(table.orderId),index("idx_order_items_product").on(table.productId)]);
export const payments = sqliteTable("payments", { id:text("id").primaryKey(), orderId:text("order_id").notNull(), provider:text("provider").notNull(), providerPaymentId:text("provider_payment_id"), status:text("status").notNull(), amount:real("amount").notNull(), idempotencyKey:text("idempotency_key").notNull(), mode:text("mode").notNull(), ...timestamps },(table)=>[uniqueIndex("idx_payments_idempotency").on(table.idempotencyKey),index("idx_payments_order").on(table.orderId)]);
export const shipments = sqliteTable("shipments", { id:text("id").primaryKey(), orderId:text("order_id").notNull(), supplierId:text("supplier_id"), trackingCode:text("tracking_code"), carrier:text("carrier"), status:text("status").notNull(), estimatedDelivery:text("estimated_delivery"), ...timestamps },(table)=>[index("idx_shipments_order").on(table.orderId),index("idx_shipments_tracking").on(table.trackingCode)]);
export const trackingEvents = sqliteTable("tracking_events", { id:integer("id").primaryKey({autoIncrement:true}), shipmentId:text("shipment_id").notNull(), status:text("status").notNull(), description:text("description").notNull(), occurredAt:text("occurred_at").notNull(), source:text("source").notNull() },(table)=>[index("idx_tracking_events_shipment_date").on(table.shipmentId,table.occurredAt)]);
export const coupons = sqliteTable("coupons", { id:text("id").primaryKey(), code:text("code").notNull(), type:text("type").notNull(), value:real("value").notNull(), active:integer("active",{mode:"boolean"}).notNull().default(false), startsAt:text("starts_at"), endsAt:text("ends_at"), ...timestamps },(table)=>[uniqueIndex("idx_coupons_code").on(table.code)]);
export const reviews = sqliteTable("reviews", { id:text("id").primaryKey(), userId:text("user_id").notNull(), productId:text("product_id").notNull(), orderItemId:text("order_item_id").notNull(), rating:integer("rating").notNull(), title:text("title"), body:text("body"), verifiedPurchase:integer("verified_purchase",{mode:"boolean"}).notNull().default(true), status:text("status").notNull().default("pending"), ...timestamps },(table)=>[uniqueIndex("idx_reviews_order_item").on(table.orderItemId),index("idx_reviews_product_status").on(table.productId,table.status)]);
export const automationEvents = sqliteTable("automation_events", { id:text("id").primaryKey(), orderId:text("order_id"), type:text("type").notNull(), status:text("status").notNull(), adapter:text("adapter"), attempt:integer("attempt").notNull().default(1), payloadJson:text("payload_json"), errorMessage:text("error_message"), ...timestamps },(table)=>[index("idx_automation_events_order_status").on(table.orderId,table.status)]);
export const webhookEvents = sqliteTable("webhook_events", { id:text("id").primaryKey(), provider:text("provider").notNull(), externalEventId:text("external_event_id").notNull(), signatureValid:integer("signature_valid",{mode:"boolean"}).notNull(), status:text("status").notNull(), payloadHash:text("payload_hash").notNull(), receivedAt:text("received_at").notNull(), processedAt:text("processed_at") },(table)=>[uniqueIndex("idx_webhook_provider_event").on(table.provider,table.externalEventId)]);
export const marginRules = sqliteTable("margin_rules", { id:text("id").primaryKey(), category:text("category").notNull(), minimumPercent:real("minimum_percent").notNull(), targetPercent:real("target_percent").notNull(), maxCostVariationPercent:real("max_cost_variation_percent").notNull(), actionOnBreach:text("action_on_breach").notNull().default("manual_review"), ...timestamps },(table)=>[uniqueIndex("idx_margin_rules_category").on(table.category)]);
export const supplierScores = sqliteTable("supplier_scores", { id:text("id").primaryKey(), supplierId:text("supplier_id").notNull(), score:real("score").notNull(), reputation:real("reputation"), dispatch:real("dispatch"), tracking:real("tracking"), stockStability:real("stock_stability"), automation:real("automation"), evaluatedAt:text("evaluated_at").notNull(), evidenceJson:text("evidence_json") },(table)=>[index("idx_supplier_scores_supplier_date").on(table.supplierId,table.evaluatedAt)]);
export const auditLogs = sqliteTable("audit_logs", { id:text("id").primaryKey(), entityType:text("entity_type").notNull(), entityId:text("entity_id").notNull(), action:text("action").notNull(), actorType:text("actor_type").notNull(), beforeJson:text("before_json"), afterJson:text("after_json"), source:text("source").notNull(), createdAt:text("created_at").notNull() },(table)=>[index("idx_audit_logs_entity_date").on(table.entityType,table.entityId,table.createdAt)]);

